openapi: 3.0.1
info:
  title: RAITO API
  description: 'This is the OpenAPI specification for the RAITO web project.'
  version: 1.0.0
tags:
- name: auth
  description: Everything about authentication
- name: query
  description: Access to querying functionality
- name: info
  description: Information about currently supported APIs.
servers:
- url: http://localhost:8080/v1
paths:
  /auth:
    get:
      tags:
       - auth
      summary: Initiate an authentication flow
      operationId: startAuth
      responses:
        200:
          description: The Google authentication endpoint.
          content:
            application/json:
              schema:
                type: object
                required: [auth, ]
                properties:
                  auth:
                    type: string
  /code:
    get:
      tags:
        - auth
      summary: The endpoint for receiving the authentication code
      operationId: consumeCode
      responses:
        200:
          description: Close the auth window and send the tokens
          content:
            text/html:
              schema:
                type: string
                example: <html><script>window.opener.postMessage('{message}', 'http://localhost:4200');window.close();/script></html>    
              
        401:
          description: Unauthorized
  /refresh:
    post:
      tags:
       - auth
      summary: Obtain new tokens
      operationId: refreshTokens
      requestBody:
        description: contains the refresh token
        content:
          application/json:
            schema:
              type: object
              required: [refresh_token]
              properties:
                refresh_token:
                  type: string
      responses:
        200:
          description: Successful generation of new tokens
          content:
            application/json:
              schema:
                type: object
                required: [refresh_token, access_token]
                properties:
                  refresh_token:
                    type: string
                  access_token:
                    type: string
        401:
          description: Unauthorized
  /query/{api}:
    get:
      parameters:
        - in: path
          name: api
          required: true
          schema:
            type: string
          description: The name of the API to be queried.
        - in: query
          name: sentence
          required: true
          schema:
            type: string
          description: The sentence to be transformed into HTTP request.
      tags:
       - query
      summary: Query the given API.
      operationId: query
      responses:
        200:
          description: Successful querying of given API.
          content:
            application/json:
              schema:
                type: object
                required: [api_response, predicted_requests]
                properties:
                  api_response:
                    type: string
                  predicted_requests:
                    type: array
                    items:
                      type: string
                    
        400:
          description: The given sentence could not be transformed.
        401:
          description: Unauthorized
      security:
        - raito_auth:
          - api:query
  /upload_api:
    post:
      summary: Upload a new openapi spec
      tags:
      - upload
      requestBody:
        content:
          application/octet-stream:
            schema:
              type: string
              format: binary
      responses:
        200:
          description: Successful upload
      security:
        - raito_auth:
          - api:query    
  /api:
    get:
      tags:
        - info
      summary: Obtain the names of the currently added APIs.
      operationId: api
      responses:
        200:
          description: Successful fetching of API name.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
      security:
        - raito_auth:
          - api:info
  /history:
    get:
      tags:
        - info
      summary: get the query history of a user(from the access token)
      operationId: history
      responses:
        200:
          description: Fetched the history
          content:
            application/json:
              schema:
                type: object
                required: [history]
                properties:
                  history:
                    type: array
                    items:
                      type: object
                      required: [user, api, result, sentence]
                      properties:
                        user:
                          type: string
                        api:
                          type: string
                        result:
                          type: string
                        sentence:
                          type: string
components:
  securitySchemes:
    raito_auth:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/v2/auth
          tokenUrl: https://oauth2.googleapis.com/token
          scopes:
            api:query: Query a given API.
            api:info: Get info about a certain API.
